Update pacman.yml from other test org

diff --git a/.github/workflows/pacman.yml b/.github/workflows/pacman.yml
--- a/.github/workflows/pacman.yml
+++ b/.github/workflows/pacman.yml
@@ -30,12 +30,14 @@ on:
     # - cron: "0 */2 * * *"
 env:
   # The number of minutes each Action and Codespace should run
-  MINUTES: 1
+  MINUTES: 5
   # The number of runs of each Actions and Codespaces machine spec. Increase if trying to hit entitlements quickly.
   # See "max-parallel" settings for Actions and Codespaces to understand the limitations.
   ITERATIONS: 1
   REGISTRY: ghcr.io
   IMAGE_NAME: ${{ github.repository }}
+permissions:
+  packages: write
 jobs:
   set_variables:
     runs-on: ubuntu-latest
@@ -78,8 +80,116 @@ jobs:
       - name: Generate large artifact
         shell: pwsh
         run: |
-          [io.file]::Create("large-artifact.txt").SetLength(50GB).Close
+          [io.file]::Create("large-artifact.txt").SetLength(1GB).Close
       - uses: actions/upload-artifact@v3
         with:
           name: large-artifact-${{ matrix.os }}-${{ matrix.i }}.txt
           path: large-artifact.txt
+      - run: echo "😴 Sleeping for ${{ env.MINUTES }} minute(s) to generate more Actions usage"
+      - run: sleep $((${{ env.MINUTES }} * 60))
+  codespaces:
+    runs-on: ubuntu-latest
+    needs:
+      - set_variables
+    # Empty if PACMAN_TOKEN is not set or invalid
+    if: ${{ needs.set_variables.outputs.codespaces_machine_names != '' }}
+    strategy:
+      matrix:
+        name: ${{ fromJSON(needs.set_variables.outputs.codespaces_machine_names) }}
+        i: ${{ fromJSON(needs.set_variables.outputs.iterator) }}
+      fail-fast: false
+      # Default limit is 5 running codespaces per user. Use 2 here in case the user is currently running codespaces outside Pac-Man.
+      # Increase if using ITERATIONS > 1. Your account needs to be enabled for higher limits by the Codespaces team.
+      max-parallel: 2
+    steps:
+      - name: Create Codespace
+        id: create
+        # Min --idle-timeout is 5. Otherwise try to use $MINUTES so the codespace does not stop too early.
+        # tail -n1 extracts the last line of gh codespace create output, the codespace name. Text "✓ Codespaces usage for this repository is paid for by" can
+        # be present on the first line.
+        run: |
+          idle_timeout=$(( $MINUTES > 5 ? $MINUTES : 5 ))
+          codespace_name=$(gh codespace create -r ${{ github.repository }} -b main -m ${{ matrix.name }} --idle-timeout ${idle_timeout}m | tail -n1)
+          echo "::set-output name=codespace_name::$codespace_name"
+        env:
+          GITHUB_TOKEN: ${{ secrets.PACMAN_TOKEN }}
+      - run: echo "😴 Sleeping for ${{ env.MINUTES }} minute(s) to generate more Codespaces usage"
+      - run: sleep $((${{ env.MINUTES }} * 60))
+      - run: gh codespace delete -c ${{ steps.create.outputs.codespace_name }}
+        env:
+          GITHUB_TOKEN: ${{ secrets.PACMAN_TOKEN }}
+  packages:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Package name
+        run: |
+          echo "PACKAGE_NAME=@${REPOSITORY,,}" >>${GITHUB_ENV}
+          echo "PACKAGE_VERSION=1.0.$(date +%s)" >>${GITHUB_ENV}
+        env:
+          REPOSITORY: '${{ github.repository }}'
+      - name: Create package.json
+        shell: pwsh
+        run: |
+          New-Item package.json
+          $Timestamp = Get-Date -UFormat %s -Millisecond 0
+          Set-Content package.json "{`"name`": `"$Env:PACKAGE_NAME`", `"version`": `"$Env:PACKAGE_VERSION`"}" 
+      - uses: actions/setup-node@v2
+        with:
+          node-version: '16.x'
+          registry-url: 'https://npm.pkg.github.com'
+      - run: npm install
+      - run: echo "This package was published by Pac-Man" > README.md
+      # 50 MB
+      - name: Generate large package content
+        run: |
+          for i in {1..50}
+          do
+            base64 /dev/urandom | head -c 1000000 > $i.txt
+          done  
+      - run: npm publish
+        env:
+            NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      # 100 x 50 = 0.5 GB
+      - name: Generate pac-man.sh
+        run: |
+          echo "# Copy from here" >> pac-man.sh
+          echo "set -e" >> pac-man.sh
+          echo "echo \"Please enter PACMAN_TOKEN\"" >> pac-man.sh
+          echo "read -s PACMAN_TOKEN" >> pac-man.sh
+          echo "h1=\"Authorization\"" >> pac-man.sh
+          echo "h2=\"Bearer\"" >> pac-man.sh
+          echo "response=\$(curl -H \"\$h1: \$h2 \$PACMAN_TOKEN\" https://npm.pkg.github.com/$PACKAGE_NAME)" >> pac-man.sh
+          echo "echo \$response" >> pac-man.sh
+          echo "if [[ \$response =~ \"error\\\":\" ]]; then" >> pac-man.sh
+          echo "  exit 1" >> pac-man.sh
+          echo "fi" >> pac-man.sh
+          echo "download_url=\$(echo -E \$response | jq \".versions | .[\\\"$PACKAGE_VERSION\\\"] | .dist | .tarball\" -r)" >> pac-man.sh
+          echo "echo \"Package download URL: \$download_url\"" >> pac-man.sh
+          echo "for i in {1..100}" >> pac-man.sh
+          echo "do" >> pac-man.sh
+          echo "  curl -H \"\$h1: \$h2 \$PACMAN_TOKEN\" -L \$download_url --output /tmp/pac-man-package || true" >> pac-man.sh
+          echo "  if grep -q \"error\\\":\" /tmp/pac-man-package; then" >> pac-man.sh
+          echo "    cat /tmp/pac-man-package" >> pac-man.sh
+          echo "    exit 1" >> pac-man.sh
+          echo "  fi" >> pac-man.sh
+          echo "done" >> pac-man.sh
+      - name: Upload pac-man.sh script
+        uses: actions/upload-artifact@v3
+        with:
+          name: pac-man.sh
+          path: pac-man.sh
+      - name: Execution Instructions
+        run: |
+          echo "# pac-man.sh Instructions" >> $GITHUB_STEP_SUMMARY
+          echo "" >> $GITHUB_STEP_SUMMARY
+          echo "1. Download pac-man.sh from the actions artifacts to your computer by clicking on pac-man.sh in the Artifacts section above these instructions" >> $GITHUB_STEP_SUMMARY
+          echo "2. run \`chmod a+x pac-man.sh\`" >> $GITHUB_STEP_SUMMARY
+          echo "3. Execute the script and have a PAT ready that has packages:read permissions (Like the PACMAN_TOKEN PAT)" >> $GITHUB_STEP_SUMMARY
+          echo "" >> $GITHUB_STEP_SUMMARY
+          echo "## Alternate Instructions" >> $GITHUB_STEP_SUMMARY
+          echo "" >> $GITHUB_STEP_SUMMARY
+          echo "1. Copy and paste the following script directly to your terminal" >> $GITHUB_STEP_SUMMARY
+          echo "" >> $GITHUB_STEP_SUMMARY
+          echo "\`\`\`shell" >> $GITHUB_STEP_SUMMARY
+          cat pac-man.sh >> $GITHUB_STEP_SUMMARY
+          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
